#!/usr/bin/env bash

fatel() {
  # echo all the args from the user to stderr
  echo '[fatel]' "$@" >&2
  exit 1
}

parse-request() {
  declare -gA REQ_INFO=()
  declare -gA REQ_HEADERS=()

  state="status"
  local line

  while read -r line; do
    # this will remove the \r from the end of the line
    line=${line%$'\r'}

    case "$state" in
    "status")
      local method path version
      read -r method path version <<<"$line"
      REQ_INFO[metohd]=$method
      REQ_INFO[path]=$path
      REQ_INFO[version]=$version
      state="headers"
      ;;
    "headers")
      if [[ -z $line ]]; then
        state="done"
        break
      fi
      local key value
      # set the separator (IFS) to :
      IFS=: read -r key value <<<"$line"
      # lowercase the key, with this notation
      key=${key,,}
      # remove whitespace from the left of the value
      value=${value# *}
      REQ_HEADERS[$key]=$value
      ;;
    "body")
      command ...
      ;;
    "done")
      break
      ;;
    esac
  done
}

  # we can write back to the file descriptor
    printf 'HTTP/1.1 200 ok\r\n' >&"$fd"
    printf 'Content-type: text/plain\r\n' >&"$fd"
    printf 'Connction: closed\r\n' >&"$fd"
    printf '\r\n' >&"$fd"

# Bash does not have a built-in way to listen on a port, but we can use loadable builtins that come with bash.
# A list of the loadable commands can be found at $BASH_LOADABLES_PATH, some systems do not come with the loadable
# builtins installed. In that case, you can build them from source form https://git.savannah.gnu.org/git/bash.git,
# you will need to place the dir in the $BASH_LOADABLES_PATH, of add it to the $BASH_LOADABLES_PATH, and follow the
# INSTALL file.
enable accept || fatel 'faild to load accept'

PORT=8080
ADDRESS='0.0.0.0'

  echo "Listening on http://$ADDRESS:$PORT"
  local fd
    accept -b "$ADDRESS" -v fd "$PORT" || fatel "feil to read from socket"

    # close the file descriptor / client
    exec {fd}>&-


